yarnPath: .yarn/releases/yarn-4.1.0.cjs
nodeLinker: node-modules
enableGlobalCache: false

compressionLevel: mixed
enableColors: true
enableProgressBars: true
enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
