# Yarn 4 Configuration
yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Disable PnP (Plug'n'Play) - usar node_modules tradicional
nodeLinker: node-modules

# Configuración de red
httpTimeout: 60000
networkTimeout: 60000

# Configuración de cache
enableGlobalCache: false
enableMirror: false

# Configuración de instalación
enableImmutableInstalls: false
checksumBehavior: update

# Configuración de logging
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard

# Configuración de plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-essentials.cjs
    spec: "@yarnpkg/plugin-essentials"
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - path: .yarn/plugins/@yarnpkg/plugin-dlx.cjs
    spec: "@yarnpkg/plugin-dlx"

# Configuración de workspace (si se necesita en el futuro)
# workspaces:
#   - packages/*

# Configuración de registry
npmRegistryServer: "https://registry.yarnpkg.com"

# Configuración de resolución de dependencias
supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64
